version: "3.9"

services:
  depguardian:
    build: .
    container_name: depguardian
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
    volumes:
      - .:/app
